# Generated by Kconfiglib (https://github.com/ulfalizer/Kconfiglib)

#
# Toolchain configuration
#
CONFIG_TOOLCHAIN_PATH="/opt/kendryte-toolchain/bin"
CONFIG_TOOLCHAIN_PREFIX="riscv64-unknown-elf-"
# end of Toolchain configuration

#
# Components configuration
#

#
# Board config
#
CONFIG_BOARD_MAIX=y
# CONFIG_BOARD_M5STICK is not set
CONFIG_LCD_DEFAULT_WIDTH=320
CONFIG_LCD_DEFAULT_HEIGHT=240
CONFIG_LCD_DEFAULT_FREQ=15000000
CONFIG_SENSOR_FREQ=24000000
# end of Board config

# CONFIG_COMPONENT_DRIVERS_ENABLE is not set
CONFIG_COMPONENT_KENDRYTE_SDK_ENABLE=y

#
# Kendryte SDK configurations
#
CONFIG_SDK_LOG_LEVEL=5
CONFIG_FREERTOS_ENABLE=y

#
# FreeRTOS configurations
#
# CONFIG_STATIC_TASK_CLEAN_UP_ENABLE is not set
# CONFIG_FREERTOS_MALLOC_CUSTOM is not set
CONFIG_FREEROTS_MINIMUM_STACK_SIZE=2048
# end of FreeRTOS configurations

# CONFIG_MIC_ARRAY_ENABLE is not set
# end of Kendryte SDK configurations

# CONFIG_COMPONENT_MICROPYTHON_ENABLE is not set
# CONFIG_COMPONENT_SPIFFS_ENABLE is not set
# CONFIG_COMPONENT_UTILS_ENABLE is not set
# end of Components configuration
